### ISSUE TITLE
Dynamic breaks ssr builds

### ISSUE THREAD

**Issue by urish** [swordev/suid#190]
Specifically, importing `SVGElements` and `getNextElement` [here](https://github.com/swordev/suid/blob/c9702576e9ea2f9a0b8be4eb380572e76fa5d1ea/packages/system/src/Dynamic/Dynamic.tsx#L15-L19) causes the build to fail with an error:

```
  binding: 'SVGElements',
  code: 'MISSING_EXPORT',
```

If I replace these imports with a star import, e.g.
```
import * as web from 'solid-js/web';
```

Then prefix any of the imported symbols with `web.`, this seems to make rollup happy and then I can successfully run the SSR build.

I can send a pull request with this change, if you are interested. But I feel like I don't understand the entire context here - e.g. there must be a reason for copying the Dynamic element from Solid source code instead of importing it.

**Comment by juanrgm** [comment]
> I can send a pull request with this change, if you are interested. But I feel like I don't understand the entire context here - e.g. there must be a reason for copying the Dynamic element from Solid source code instead of importing it.

The `Dynamic` components aren't equals. There is a conflict with the `component` property and it's renamed to `$component` here:
 https://github.com/swordev/suid/blob/c9702576e9ea2f9a0b8be4eb380572e76fa5d1ea/packages/system/src/Dynamic/Dynamic.tsx#L53

The cause is than `MUI` uses that property for overriding the element in last instance, but the original `Dynamic` component replaces directly the component.

There are some tests about this here: https://github.com/swordev/suid/blob/7c1cec6f50d6dfbadf11cc96a28f01c15732240f/packages/system/src/Dynamic/Dynamic.test.tsx#L5

**Comment by urish** [comment]
> Is import * as web from 'solid-js/web' a problem for tree shaking?

As far as I can tell, rollup picks it up correctly in my case. This is what the generated code looks like after the rollup transform:

```js
function ServerDynamic(props) {
  const [p, others] = splitProps(props, ["$component"]);
  const comp = p.$component,
    t = typeof comp;
  if (comp) {
    if (t === "function") return comp(others);else if (t === "string") {
      return ssrElement(comp, others, undefined, true);
    }
  }
}
// https://github.com/solidjs/solid/blob/12c0dbbbf9f9fdf798c6682e57aee8ea763cf1ba/packages/solid/web/src/index.ts#L114
function Dynamic(props) {
  return ServerDynamic(props);
}
```

So the client side code get eliminated correctly. No mention of `SVGElements` or `getNextElement` is the generated code, but `isServer` and `ssrElement` are included (since they are used by the server-side code). So it seems to tree shake correctly.
