### ISSUE TITLE
TextField multiline property not working

### ISSUE THREAD

**Issue by paul-wery** [swordev/suid#89]
Using TextField multiline property is not working. 
Checking the DOM it seems <input> tag has not been replaced by a <textarea> tag as doing material ui in React

**Comment by T3ch0o** [comment]
There's workaround, you can replace it through InputProps { inputComponent: 'textarea' }

**Comment by evlist** [comment]
This workaround doesn't work with suid/material 0.9.1and raises an error (TypeError: Cannot set property type of #<HTMLTextAreaElement> which has only a getter) at InputBase.jsx:310.

**Comment by evlist** [comment]
Commenting lines 309 to 315 fixes this error but will probably have side effects !

**Comment by evlist** [comment]
In fact the issue is that HTMLTextAreaElement has a type property (with "textarea" has a value) and this type property is read only while HTMLInputElement has a read/write type property.

A better patch is to leave these lines as they are and add the value "textarea" to the selectionTypes set (line 241):
```
const selectionTypes = new Set(["text", "textarea", "search", "password", "tel", "url"]);
```
